// ========================================================
// VAULT BREAKER - QUESTIONS DATABASE
// ========================================================
// This file contains all questions for each vault type.
// Add more questions to increase variety!
// ========================================================

const VaultQuestions = {
    
    // ========== VAULT 1: RIDDLE QUESTIONS ==========
    riddleTemplates: [
        // Template 1: "I have X but cannot Y"
        {
            template: "I have {count} {items}, but I cannot {action}. What am I?",
            options: [
                { count: "hands", items: "", action: "clap", answer: "clock", hint: "Tells time" },
                { count: "a face", items: "", action: "smile", answer: "clock", hint: "Hangs on wall" },
                { count: "teeth", items: "", action: "eat", answer: "comb", hint: "Used for hair" },
                { count: "keys", items: "", action: "open doors", answer: "keyboard", hint: "Used for typing" },
                { count: "legs", items: "", action: "walk", answer: "table", hint: "Furniture" },
                { count: "an eye", items: "", action: "see", answer: "needle", hint: "Used in sewing" },
                { count: "a head", items: "", action: "think", answer: "nail", hint: "Used with hammer" },
                { count: "ears", items: "", action: "hear", answer: "corn", hint: "A vegetable" },
                { count: "a tongue", items: "", action: "taste", answer: "shoe", hint: "Worn on feet" },
                { count: "a neck", items: "", action: "swallow", answer: "bottle", hint: "Holds liquid" },
                { count: "pages", items: "", action: "read", answer: "book", hint: "Found in library" },
                { count: "hands", items: "", action: "hold anything", answer: "watch", hint: "On your wrist" },
                { count: "a spine", items: "", action: "move", answer: "book", hint: "Contains stories" },
                { count: "bark", items: "", action: "bite", answer: "tree", hint: "Grows in forests" },
                { count: "rings", items: "", action: "wear them", answer: "tree", hint: "Has branches" },
                { count: "wings", items: "", action: "fly", answer: "building", hint: "Has many floors" },
                { count: "a bed", items: "", action: "sleep", answer: "river", hint: "Water flows here" },
                { count: "four feet", items: "", action: "walk", answer: "bed", hint: "Sleep on it" },
                { count: "a mouth", items: "", action: "speak", answer: "river", hint: "Flows to sea" },
                { count: "holes", items: "", action: "hold water", answer: "sponge", hint: "Used for cleaning" }
            ]
        },
        // Template 2: "Gets X when you Y"
        {
            template: "What gets {comparison} the more you {action}?",
            options: [
                { comparison: "wetter", action: "dry", answer: "towel", hint: "Found in bathroom" },
                { comparison: "shorter", action: "use it", answer: "candle", hint: "Gives light" },
                { comparison: "smaller", action: "add to it", answer: "hole", hint: "Empty space" },
                { comparison: "bigger", action: "take from it", answer: "hole", hint: "In the ground" },
                { comparison: "less", action: "see", answer: "darkness", hint: "Night time" },
                { comparison: "sharper", action: "use it", answer: "brain", hint: "Think with it" },
                { comparison: "fuller", action: "give it away", answer: "heart", hint: "Feel with it" },
                { comparison: "longer", action: "cut it", answer: "road", hint: "Drive on it" },
                { comparison: "thinner", action: "add to it", answer: "silence", hint: "No sound" },
                { comparison: "heavier", action: "carry it", answer: "guilt", hint: "A feeling" }
            ]
        },
        // Template 3: "Can X but cannot Y"
        {
            template: "I can {ability1} but cannot {ability2}. What am I?",
            options: [
                { ability1: "fly without wings", ability2: "walk", answer: "time", hint: "Always moving" },
                { ability1: "run but never walk", ability2: "talk", answer: "river", hint: "Water body" },
                { ability1: "be broken without being touched", ability2: "be fixed", answer: "promise", hint: "A commitment" },
                { ability1: "travel the world while staying in a corner", ability2: "move", answer: "stamp", hint: "On letters" },
                { ability1: "be caught but not thrown", ability2: "be held", answer: "cold", hint: "An illness" },
                { ability1: "fill a room", ability2: "be touched", answer: "light", hint: "From the sun" },
                { ability1: "be cracked", ability2: "be held", answer: "joke", hint: "Makes you laugh" },
                { ability1: "wave", ability2: "swim", answer: "flag", hint: "On a pole" },
                { ability1: "speak without a mouth", ability2: "hear", answer: "echo", hint: "Sound bouncing" },
                { ability1: "fall but never get hurt", ability2: "walk", answer: "rain", hint: "From clouds" },
                { ability1: "point in every direction", ability2: "reach anywhere", answer: "compass", hint: "Navigation tool" },
                { ability1: "go up and never come down", ability2: "fall", answer: "age", hint: "Gets bigger" },
                { ability1: "be held without hands", ability2: "be touched", answer: "breath", hint: "You do it always" },
                { ability1: "be made but not seen", ability2: "be touched", answer: "noise", hint: "Heard by ears" },
                { ability1: "travel around the world in a corner", ability2: "leave the corner", answer: "stamp", hint: "Mail needs it" }
            ]
        },
        // Template 4: Classic riddles
        {
            template: "{question}",
            options: [
                { question: "What has a head and tail but no body?", answer: "coin", hint: "Money" },
                { question: "What can you catch but not throw?", answer: "cold", hint: "An illness" },
                { question: "What has hands but can't clap?", answer: "clock", hint: "Tells time" },
                { question: "What can travel around the world while staying in a corner?", answer: "stamp", hint: "On envelopes" },
                { question: "What has a ring but no finger?", answer: "phone", hint: "You call with it" },
                { question: "What gets broken without being held?", answer: "promise", hint: "A word given" },
                { question: "What can you break without touching?", answer: "silence", hint: "Quiet" },
                { question: "What is always in front of you but can't be seen?", answer: "future", hint: "Tomorrow" },
                { question: "What can fill a room but takes no space?", answer: "light", hint: "Sun gives it" },
                { question: "What word becomes shorter when you add letters to it?", answer: "short", hint: "Opposite of long" },
                { question: "What goes up but never comes down?", answer: "age", hint: "Birthday adds to it" },
                { question: "What is full of holes but holds water?", answer: "sponge", hint: "For cleaning" },
                { question: "What can run but never walks?", answer: "water", hint: "In rivers" },
                { question: "What has one eye but cannot see?", answer: "needle", hint: "Sewing tool" },
                { question: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "m", hint: "A letter" },
                { question: "What five-letter word becomes shorter when you add two letters to it?", answer: "short", hint: "Opposite of tall" },
                { question: "What belongs to you but others use it more than you?", answer: "name", hint: "Identity" },
                { question: "What is so fragile that saying its name breaks it?", answer: "silence", hint: "No sound" },
                { question: "What has words but never speaks?", answer: "book", hint: "Has pages" },
                { question: "What has a bottom at the top?", answer: "leg", hint: "Body part" }
            ]
        }
    ],

    // ========== VAULT 2: DIAMOND MINE (no questions, just game config) ==========
    diamondMineConfig: {
        gridSize: 9,
        bombCount: 3,
        requiredHearts: 3
    },

    // ========== VAULT 3: BOLLYWOOD EMOJI MOVIES ==========
    bollywoodMovies: [
        // Classic Movies
        { name: "sholay", keywords: ["desert", "villain", "friends", "revenge"], emojis: ["💀", "🏜️", "🔫", "🐴", "🔥",] },
        { name: "ddlj", keywords: ["train", "love", "europe", "bride"], emojis: ["🚂", "💕", "👰", "🌾", "🎻", "💒"] },
        { name: "lagaan", keywords: ["cricket", "british", "village", "tax"], emojis: ["🏏", "🇮🇳", "🏆", "🌾", "👨‍🌾"] },
        { name: "3idiots", keywords: ["college", "engineering", "friends", "comedy"], emojis: ["3️⃣", "🎓", "😂", "🧠", "📚",] },
        { name: "dangal", keywords: ["wrestling", "daughters", "father", "gold"], emojis: ["🤼", "👧", "💪", "🥇", "🏆", "👨‍👧"] },
        { name: "pk", keywords: ["alien", "god", "questions", "comedy"], emojis: ["👽", "❓", "🛕", "😂", "📻", "🤔"] },
        { name: "bahubali", keywords: ["king", "war", "mother", "waterfall"], emojis: ["👑", "⚔️", "💪", "🦅", "🏰"] },
        { name: "krish", keywords: ["superhero", "mask", "flying", "alien"], emojis: ["🦸", "🎭", "✨", "👽", "💫"] },
        { name: "dhoom", keywords: ["bike", "thief", "chase", "action"], emojis: ["🏍️", "💰", "🏎️", "💨"] },
        { name: "golmaal", keywords: ["comedy", "friends", "funny", "chaos"], emojis: ["😂", "👨‍👨‍👦‍👦", "🤪", "🤣", "👻"] },
        { name: "singham", keywords: ["police", "action", "honest", "villain"], emojis: ["👮", "💪", "⚖️", "🚔", "👊"] },
        
        // Modern Hits
        { name: "sultan", keywords: ["wrestling", "comeback", "champion"], emojis: ["🤼", "💪", "🏆", "🥇", "👊"] },
        { name: "uri", keywords: ["army", "surgical", "strike", "pakistan"], emojis: ["🎖️", "🔫", "🇮🇳", "💥", "🦅"] },
        { name: "padmaavat", keywords: ["queen", "rajput", "jauhar", "king"], emojis: ["👸", "🔥", "⚔️", "👑", "🏰", "💃"] },
        { name: "rockstar", keywords: ["singer", "music", "heartbreak", "fame"], emojis: ["🎸", "🎤", "💔", "🌟", "🎵", "😢"] },
        { name: "stree", keywords: ["ghost", "woman", "village", "horror"], emojis: ["👻", "👩", "🌙", "😱", "🏘️", "🔔"] },
        { name: "gangs", keywords: ["wasseypur", "coal", "mafia", "revenge"], emojis: ["🔫", "⛏️", "😈", "💀", "🎯", "🔪"] },
        { name: "zindaginamilegidobara", keywords: ["milegi", "spain", "friends", "travel"], emojis: ["✈️", "🎉", "🏃", "🌍"] },
        
        // Emotional/Drama
        { name: "taarezameen", keywords: ["zameen", "dyslexia", "teacher", "child"], emojis: ["⭐", "👦", "🎨", "👨‍🏫", "📖",] },
        { name: "chakdeindia", keywords: ["hockey", "india", "coach", "victory"], emojis: ["🏑", "🇮🇳", "🏆", "💪", "🥇", "👨‍🏫"] },
        
        { name: "ghajini", keywords: ["memory", "revenge", "tattoo", "villain"], emojis: ["🧠", "📝", "💪", "😠", "🔪", "💀"] },
        { name: "race", keywords: ["cars", "brothers", "twist", "murder"], emojis: ["🏎️", "👔", "💰", "🎭"] },
        { name: "drishyam", keywords: ["family", "murder", "hide", "clever"], emojis: ["👨‍👩‍👧‍👦", "🔍", "🔪", "🧠", "📺", "😰"] },
        { name: "kahaani", keywords: ["pregnant", "kolkata", "spy", "revenge"], emojis: ["🤰", "🔍", "🕵️", "💥", "🚇", "👩"] },
        { name: "queen", keywords: ["paris", "honeymoon", "alone", "freedom"], emojis: ["👰", "🇫🇷", "✈️", "💃", "🗼", "🎉"] },
        
        // Historical/Patriotic
        { name: "munnabhai", keywords: ["mbbs", "doctor", "gandhigiri", "comedy"], emojis: ["🏥", "🌹", "😂", "👨‍⚕️", "💉"] },
        { name: "lunchbox", keywords: ["dabba", "letters", "love", "food"], emojis: ["🍱", "💌", "❤️", "🚂", "✍️", "🥘"] },
        { name: "article15", keywords: ["caste", "police", "village", "justice"], emojis: ["⚖️", "👮", "🏘️", "✊", "🔍", "📋"] },
        
        // Recent Hits
        { name: "raazi", keywords: ["spy", "pakistan", "woman", "marriage"], emojis: ["🕵️‍♀️", "🇵🇰", "💍", "🇮🇳", "📻", "🤫"] },
        { name: "gullyboy", keywords: ["rapper", "mumbai", "slum", "music"], emojis: ["🎤", "🏙️", "🎵", "✊", "🎧", "🔥"] },
        { name: "kesari", keywords: ["sikh", "battle", "saragarhi", "brave"], emojis: ["🧡", "⚔️", "💪", "🇮🇳", "🦁"] },
        { name: "missionmangal", keywords: ["mangal", "space", "isro", "women"], emojis: ["🚀", "🔴", "👩‍🔬", "🇮🇳", "🌌", "💫"] },
        { name: "bala", keywords: ["bald", "comedy", "confidence", "love"], emojis: ["👨‍🦲", "😂", "💪", "❤️", "😅"] },
        
        // Additional Movies
        { name: "kabirsingh", keywords: ["singh", "love", "doctor", "anger"], emojis: ["👨‍⚕️", "💔", "😠", "❤️", "🏥", "💊"] },
        { name: "sanju", keywords: ["drugs", "prison", "bollywood", "father"], emojis: ["🎬", "⛓️", "💊", "👴", "😢"] },
        { name: "padman", keywords: ["pads", "women", "invention", "village"], emojis: ["🩸", "👩", "💡", "🚽", "❤️", "🏆"] },
        { name: "toilet", keywords: ["toilet", "village", "marriage", "change"], emojis: ["🚽", "👰", "🏘️", "✊", "❤️", "🏠"] },
        { name: "chhichhore", keywords: ["college", "suicide", "friends", "life"], emojis: ["🎓", "👨‍👨‍👦‍👦", "🏆", "❤️", "🎉"] },
        { name: "super30", keywords: ["teacher", "iit", "poor", "students"], emojis: ["👨‍🏫", "📚", "🎓", "3️⃣0️⃣", "✨"] },
        { name: "war", keywords: ["action", "soldier", "betrayal", "fight"], emojis: ["🔫", "💥", "🎖️", "✈️", "👊", "🏍️"] },
        { name: "goodnewz", keywords: ["newwz", "baby", "ivf", "comedy"], emojis: ["👶", "💉", "😂", "👨‍👩‍👧", "🏥", "❤️"] },
        { name: "tanhaji", keywords: ["maratha", "fort", "warrior", "battle"], emojis: ["⚔️", "🏰", "🇮🇳", "🦁", "🏹", "💪"] },
        { name: "shershaah", keywords: ["army", "kargil", "war", "hero"], emojis: ["🎖️", "🇮🇳", "🏔️", "💪", "🔫", "❤️"] },
        { name: "animal", keywords: ["father", "son", "dark", "mafia"], emojis: ["🐺", "👨‍👦", "🔫", "💰", "😈", "💔"] },
        
        // More Classic Bollywood
        { name: "mughal", keywords: ["mughal", "azam", "love", "emperor"], emojis: ["👑", "💕", "🏰", "⚔️", "🌹"] },
        { name: "devdas", keywords: ["love", "alcohol", "tragedy", "dance"], emojis: ["🍷", "💔", "💃", "😢", "🪔"] },
        { name: "kabhi", keywords: ["khushi", "gham", "family", "emotions"], emojis: ["👨‍👩‍👧‍👦", "😢", "😊", "🏠", "❤️"] },
        { name: "kuch", keywords: ["kuch", "hota", "college", "love"], emojis: ["🎓", "❤️", "🎸", "💃", "🎭"] },
        { name: "dilwale", keywords: ["love", "family", "nri", "romance"], emojis: ["❤️", "✈️", "👨‍👩‍👧", "🎻", "🌾"] },
        { name: "hera", keywords: ["pheri", "comedy", "scam", "money"], emojis: ["😂", "💰", "🤥", "👴", "🏠"] },
        { name: "welcome", keywords: ["comedy", "gangster", "wedding", "funny"], emojis: ["😂", "🔫", "💒", "💰", "🤣"] },
        { name: "dhamaal", keywords: ["comedy", "treasure", "friends", "chaos"], emojis: ["😂", "💎", "🗺️", "✈️", "🤪"] },
        { name: "housefull", keywords: ["comedy", "confusion", "marriage", "funny"], emojis: ["😂", "💒", "🏠", "🤯", "👨‍👩‍👧‍👦"] },
        { name: "rowdy", keywords: ["rathore", "police", "action", "comedy"], emojis: ["👮", "😎", "🔫", "😂", "💪"] },
        { name: "dabangg", keywords: ["police", "action", "salman", "villain"], emojis: ["👮", "😎", "🔫", "💪", "🏍️"] },
        { name: "bajirao", keywords: ["mastani", "warrior", "love", "history"], emojis: ["⚔️", "❤️", "🏰", "👑", "💃"] },
        { name: "jodha", keywords: ["akbar", "mughal", "love", "emperor"], emojis: ["👑", "❤️", "🏰", "⚔️", "👸"] },
        
        // More Recent Movies
        { name: "pathaan", keywords: ["spy", "action", "agent", "villain"], emojis: ["🕵️", "🔫", "💥", "✈️", "😎"] },
        { name: "jawan", keywords: ["action", "revenge", "metro", "women"], emojis: ["🚇", "🔫", "💪", "👩", "🔥"] },
        { name: "dunki", keywords: ["immigration", "friends", "donkey", "dream"], emojis: ["✈️", "🫏", "👨‍👨‍👦", "🌍", "💭"] },
        { name: "tiger", keywords: ["spy", "action", "pakistan", "love"], emojis: ["🐅", "🔫", "🇵🇰", "❤️", "💥"] },
        { name: "bhool", keywords: ["bhulaiyaa", "ghost", "comedy", "horror"], emojis: ["👻", "😂", "🏚️", "💃", "😱"] },
        { name: "rrr", keywords: ["freedom", "british", "friends", "action"], emojis: ["🔥", "💪", "🇮🇳", "⚔️", "🐅"] },
        { name: "pushpa", keywords: ["smuggler", "redwood", "rise", "power"], emojis: ["🪵", "💪", "🔫", "👑", "🔥"] },
        { name: "kgf", keywords: ["gold", "gangster", "power", "mother"], emojis: ["⛏️", "💰", "🔫", "👑", "💪"] },
        { name: "brahmastra", keywords: ["astra", "fire", "love", "powers"], emojis: ["🔥", "✨", "❤️", "💫", "⚡"] },
        { name: "gangubai", keywords: ["brothel", "woman", "power", "mumbai"], emojis: ["👩", "💪", "🏙️", "👑", "🌹"] },
        { name: "12thfail", keywords: ["upsc", "struggle", "success", "police"], emojis: ["📚", "👮", "💪", "🏆", "😢"] },
        { name: "sam", keywords: ["bahadur", "army", "war", "general"], emojis: ["🎖️", "⚔️", "🇮🇳", "💪", "🪖"] },
        { name: "fighter", keywords: ["airforce", "action", "pilot", "war"], emojis: ["✈️", "🔫", "💥", "🇮🇳", "💪"] },
        { name: "crew", keywords: ["airhostess", "heist", "comedy", "women"], emojis: ["✈️", "💰", "👩", "😂", "💎"] },
        { name: "kalki", keywords: ["future", "scifi", "avatar", "mythology"], emojis: ["🤖", "🔮", "⚔️", "🌌", "✨"] },
        { name: "rocky", keywords: ["rani", "love", "drama", "family"], emojis: ["❤️", "👨‍👩‍👧", "😢", "💔", "🎭"] },
        { name: "oppenheimer", keywords: ["bomb", "scientist", "nuclear", "war"], emojis: ["💣", "👨‍🔬", "☢️", "🔬", "💥"] },
        { name: "laal", keywords: ["singh", "chaddha", "remake", "journey"], emojis: ["🏃", "🎖️", "❤️", "🦐", "🏏"] }
    ],

    // ========== VAULT 4: SCRAMBLED WORDS ==========
    scrambledWords: [
        // Easy Words (6-7 letters)
        { word: "planet", hint: "Earth is one" },
        { word: "garden", hint: "Where plants grow" },
        { word: "window", hint: "Glass in wall" },
        { word: "bridge", hint: "Crosses a river" },
        { word: "castle", hint: "Where kings lived" },
        { word: "jungle", hint: "Dense forest" },
        { word: "silver", hint: "Precious metal" },
        { word: "dragon", hint: "Fire breathing creature" },
        { word: "flower", hint: "Roses are these" },
        { word: "monkey", hint: "Swings on trees" },
        { word: "rabbit", hint: "Hops around" },
        { word: "guitar", hint: "String instrument" },
        { word: "sunset", hint: "Evening sky view" },
        { word: "camera", hint: "Takes photos" },
        { word: "market", hint: "Buy things here" },
        { word: "temple", hint: "Place of worship" },
        { word: "forest", hint: "Many trees together" },
        { word: "police", hint: "Law enforcement" },
        { word: "circus", hint: "Clowns perform here" },
        { word: "puzzle", hint: "Brain teaser" },
        
        // Medium Words (8 letters)
        { word: "computer", hint: "Electronic device for computing" },
        { word: "keyboard", hint: "Used for typing" },
        { word: "elephant", hint: "Large animal with trunk" },
        { word: "mountain", hint: "Very tall landform" },
        { word: "building", hint: "Structure where people live or work" },
        { word: "hospital", hint: "Place for medical treatment" },
        { word: "universe", hint: "Everything that exists" },
        { word: "airplane", hint: "Flying vehicle" },
        { word: "birthday", hint: "Annual celebration of birth" },
        { word: "painting", hint: "Art created with colors" },
        { word: "shopping", hint: "Buying things from stores" },
        { word: "swimming", hint: "Moving in water" },
        { word: "football", hint: "Popular sport with ball" },
        { word: "children", hint: "Young humans" },
        { word: "sandwich", hint: "Food between bread slices" },
        { word: "calendar", hint: "Shows days and months" },
        { word: "treasure", hint: "Valuable hidden items" },
        { word: "dinosaur", hint: "Extinct giant reptile" },
        { word: "password", hint: "Secret login code" },
        { word: "midnight", hint: "12 AM" },
        { word: "sunshine", hint: "Light from the sun" },
        { word: "mushroom", hint: "Fungi that you can eat" },
        { word: "dolphin", hint: "Smart sea mammal" },
        { word: "umbrella", hint: "Rain protection" },
        { word: "firework", hint: "Explodes with colors" },
        { word: "notebook", hint: "Write notes in it" },
        { word: "backpack", hint: "Carry on your back" },
        { word: "pancakes", hint: "Breakfast food" },
        { word: "diamonds", hint: "Expensive gemstones" },
        { word: "whispers", hint: "Quiet speaking" },
        
        // Hard Words (9+ letters)
        { word: "chocolate", hint: "Sweet brown treat" },
        { word: "butterfly", hint: "Colorful flying insect" },
        { word: "adventure", hint: "Exciting experience" },
        { word: "beautiful", hint: "Very pleasing to look at" },
        { word: "breakfast", hint: "Morning meal" },
        { word: "celebrate", hint: "Mark a special occasion" },
        { word: "dangerous", hint: "Could cause harm" },
        { word: "education", hint: "Learning and teaching" },
        { word: "fantastic", hint: "Extremely good" },
        { word: "gardening", hint: "Growing plants" },
        { word: "happiness", hint: "State of joy" },
        { word: "important", hint: "Of great significance" },
        { word: "knowledge", hint: "Information and understanding" },
        { word: "lightning", hint: "Electric flash in sky" },
        { word: "nightmare", hint: "Bad scary dream" },
        { word: "orchestra", hint: "Large music group" },
        { word: "pineapple", hint: "Tropical spiky fruit" },
        { word: "questions", hint: "Things you ask" },
        { word: "rectangle", hint: "Four-sided shape" },
        { word: "skyscraper", hint: "Very tall building" },
        { word: "telephone", hint: "Device for calling" },
        { word: "vegetable", hint: "Plant food like carrot" },
        { word: "wonderful", hint: "Causing wonder" },
        { word: "xylophone", hint: "Musical instrument with bars" },
        { word: "yesterday", hint: "Day before today" },
        { word: "crocodile", hint: "Large reptile in water" },
        { word: "democracy", hint: "Government by the people" },
        { word: "fireworks", hint: "Explosive lights in sky" },
        { word: "honeybees", hint: "Insects that make honey" },
        { word: "invisible", hint: "Cannot be seen" },
        { word: "jellyfish", hint: "Sea creature with tentacles" },
        { word: "kangaroos", hint: "Jumping Australian animal" },
        { word: "waterfall", hint: "Water falling from height" },
        { word: "basketball", hint: "Sport with hoops" },
        { word: "strawberry", hint: "Red fruit" },
        { word: "flashlight", hint: "Portable light" },
        { word: "sunflower", hint: "Tall yellow flower" },
        { word: "earthquake", hint: "Ground shaking" },
        { word: "volleyball", hint: "Beach sport" },
        { word: "rhinoceros", hint: "Animal with horn" },
        { word: "helicopter", hint: "Flying with rotors" },
        { word: "microphone", hint: "Amplifies voice" },
        { word: "greenhouse", hint: "Grow plants inside" },
        { word: "skateboard", hint: "Rolling toy" },
        { word: "lighthouse", hint: "Guides ships" },
        { word: "dragonfly", hint: "Flying insect" },
        { word: "snowflakes", hint: "Frozen precipitation" },
        { word: "toothbrush", hint: "Cleans teeth" },
        { word: "fingernail", hint: "On your fingers" },
        { word: "newspaper", hint: "Daily reading" }
    ],

    // ========== VAULT 5: GENERAL KNOWLEDGE (MODERATE-DIFFICULT) ==========
    gkCategories: {
        science: [
            { q: "What is the powerhouse of the cell?", a: "mitochondria" },
            { q: "What gas makes up about 78% of Earth's atmosphere?", a: "nitrogen" },
            { q: "What is the only metal that is liquid at room temperature?", a: "mercury" },
            { q: "What is the most abundant element in the universe?", a: "hydrogen" },
            { q: "What is the process by which plants make their food called?", a: "photosynthesis" },
            { q: "What blood type is known as the universal donor?", a: "o" },
            { q: "What is the largest internal organ in the human body?", a: "liver" },
            { q: "What is the study of earthquakes called?", a: "seismology" },
            { q: "What planet rotates on its side?", a: "uranus" },
            { q: "What is the name of the largest moon of Saturn?", a: "titan" },
            { q: "What particle in an atom has no charge?", a: "neutron" },
            { q: "What is the term for animals that are active at night?", a: "nocturnal" },
            { q: "What is the hardest known natural material?", a: "diamond" },
            { q: "What is the SI unit of electric current?", a: "ampere" },
            { q: "What vitamin deficiency causes scurvy?", a: "c" },
            { q: "What is the scientific name for the collarbone?", a: "clavicle" },
            { q: "What is the study of fungi called?", a: "mycology" },
            { q: "What is the name of Mars's largest moon?", a: "phobos" },
            { q: "What element has the symbol 'K' on the periodic table?", a: "potassium" },
            { q: "What is the smallest bone in the human body?", a: "stapes" },
            { q: "What is the process of cell division called?", a: "mitosis" },
            { q: "What is the study of insects called?", a: "entomology" },
            { q: "What is the hottest planet in our solar system?", a: "venus" },
            { q: "What type of rock is formed from cooled lava?", a: "ignite" },
            { q: "What is the pH level of pure water?", a: "7" }
        ],
        geography: [
            { q: "What is the driest continent on Earth?", a: "antarctica" },
            { q: "What is the only country to span both Europe and Asia?", a: "turkey" },
            { q: "What sea is the saltiest in the world?", a: "dead" },
            { q: "What African country was formerly known as Abyssinia?", a: "ethiopia" },
            { q: "What is the capital of New Zealand?", a: "wellington" },
            { q: "What is the longest mountain range in the world?", a: "andes" },
            { q: "What strait separates Europe from Africa?", a: "gibraltar" },
            { q: "What is the largest landlocked country in the world?", a: "kazakhstan" },
            { q: "What river flows through the Grand Canyon?", a: "colorado" },
            { q: "What is the smallest continent by land area?", a: "australia" },
            { q: "What country has the most islands in the world?", a: "sweden" },
            { q: "What is the capital of South Korea?", a: "seoul" },
            { q: "What is the deepest lake in the world?", a: "baikal" },
            { q: "What desert covers most of northern Africa?", a: "sahara" },
            { q: "What is the capital of Argentina?", a: "buenos" },
            { q: "What mountain is the tallest when measured from base to peak?", a: "mauna" },
            { q: "What country is known as the Land of the Rising Sun?", a: "japan" },
            { q: "What is the largest bay in the world?", a: "bengal" },
            { q: "What European country has the most UNESCO World Heritage sites?", a: "italy" },
            { q: "What is the capital of Thailand?", a: "bangkok" },
            { q: "What African country has the largest population?", a: "nigeria" },
            { q: "What is the longest river in Asia?", a: "yangtze" },
            { q: "What country is home to Machu Picchu?", a: "peru" },
            { q: "What is the capital of Vietnam?", a: "hanoi" },
            { q: "What peninsula contains Spain and Portugal?", a: "iberian" }
        ],
        history: [
            { q: "In what year did the Berlin Wall fall?", a: "1989" },
            { q: "Who was the first woman to win a Nobel Prize?", a: "curie" },
            { q: "What empire was ruled by Genghis Khan?", a: "mongol" },
            { q: "In what year did the Titanic sink?", a: "1912" },
            { q: "Who painted the ceiling of the Sistine Chapel?", a: "michelangelo" },
            { q: "What ancient wonder was located in Alexandria?", a: "lighthouse" },
            { q: "Who was the first President of the United States?", a: "washington" },
            { q: "What year did World War I begin?", a: "1914" },
            { q: "Who discovered penicillin?", a: "fleming" },
            { q: "What ship brought the Pilgrims to America?", a: "mayflower" },
            { q: "Who was the last Pharaoh of ancient Egypt?", a: "cleopatra" },
            { q: "In what year did the French Revolution begin?", a: "1789" },
            { q: "Who wrote 'The Communist Manifesto'?", a: "marx" },
            { q: "What ancient city was destroyed by Mount Vesuvius?", a: "pompeii" },
            { q: "Who was the first person to circumnavigate the globe?", a: "magellan" },
            { q: "What year did India gain independence from Britain?", a: "1947" },
            { q: "Who was known as the Iron Lady?", a: "thatcher" },
            { q: "What war was fought between the North and South in USA?", a: "civil" },
            { q: "Who founded the Maurya Empire in India?", a: "chandragupta" },
            { q: "In what year did the Soviet Union collapse?", a: "1991" },
            { q: "Who led India's Salt March in 1930?", a: "gandhi" },
            { q: "What treaty ended World War I?", a: "versailles" },
            { q: "Who was the first man in space?", a: "gagarin" },
            { q: "What civilization built the pyramids of Giza?", a: "egyptian" },
            { q: "Who invented the printing press?", a: "gutenberg" }
        ],
        sports: [
            { q: "What country has won the most FIFA World Cups?", a: "brazil" },
            { q: "How many Grand Slam tournaments are there in tennis?", a: "4" },
            { q: "What is the only country to have played in every FIFA World Cup?", a: "brazil" },
            { q: "How many points is a try worth in rugby union?", a: "5" },
            { q: "What is the maximum score possible in a single frame of bowling?", a: "30" },
            { q: "Which city hosted the first modern Olympic Games in 1896?", a: "athens" },
            { q: "How many players are on a cricket team?", a: "11" },
            { q: "What is the distance of a marathon in kilometers (round)?", a: "42" },
            { q: "What country invented the sport of golf?", a: "scotland" },
            { q: "How many rings are on the Olympic flag?", a: "5" },
            { q: "What is the term for three strikes in a row in bowling?", a: "turkey" },
            { q: "Which Grand Slam tennis tournament is played on clay?", a: "french" },
            { q: "What is the highest possible break in snooker?", a: "147" },
            { q: "How many dimples are typically on a golf ball?", a: "336" },
            { q: "What is the national sport of Japan?", a: "sumo" },
            { q: "How many players are on a polo team?", a: "4" },
            { q: "What year were women first allowed to compete in the Olympics?", a: "1900" },
            { q: "What is the only sport to have been played on the moon?", a: "golf" },
            { q: "How many weight classes are in Olympic boxing?", a: "13" },
            { q: "What country has won the most Olympic gold medals in history?", a: "usa" },
            { q: "How long is an NBA basketball court in feet?", a: "94" },
            { q: "What is the oldest tennis tournament in the world?", a: "wimbledon" },
            { q: "How many substitutions are allowed in a football match?", a: "5" },
            { q: "What is the diameter of a basketball hoop in inches?", a: "18" },
            { q: "Which Indian cricketer is known as 'The Wall'?", a: "dravid" }
        ],
        arts: [
            { q: "Who painted the Mona Lisa?", a: "vinci" },
            { q: "What is the name of the famous painting by Edvard Munch?", a: "scream" },
            { q: "Who wrote 'Romeo and Juliet'?", a: "shakespeare" },
            { q: "What musical instrument has 88 keys?", a: "piano" },
            { q: "Who composed 'Moonlight Sonata'?", a: "beethoven" },
            { q: "What art movement is Salvador Dali associated with?", a: "surrealism" },
            { q: "Who sculpted 'The Thinker'?", a: "rodin" },
            { q: "What is the Japanese art of paper folding called?", a: "origami" },
            { q: "Who wrote 'Pride and Prejudice'?", a: "austen" },
            { q: "What is the highest female singing voice called?", a: "soprano" },
            { q: "Who painted 'The Starry Night'?", a: "gogh" },
            { q: "What musical is known for 'Memory' song?", a: "cats" },
            { q: "Who wrote '1984' and 'Animal Farm'?", a: "orwell" },
            { q: "What is the art of beautiful handwriting called?", a: "calligraphy" },
            { q: "Who composed 'The Four Seasons'?", a: "vivaldi" },
            { q: "What nationality was the composer Mozart?", a: "austrian" },
            { q: "Who wrote 'The Great Gatsby'?", a: "fitzgerald" },
            { q: "What is the lowest male singing voice called?", a: "bass" },
            { q: "Who painted 'The Last Supper'?", a: "vinci" },
            { q: "What instrument does a philatelist collect?", a: "stamps" },
            { q: "Who wrote 'War and Peace'?", a: "tolstoy" },
            { q: "What is the traditional Japanese theatre form with elaborate makeup?", a: "kabuki" },
            { q: "Who composed the opera 'Carmen'?", a: "bizet" },
            { q: "What painting technique uses small dots of color?", a: "pointillism" },
            { q: "Who wrote 'The Odyssey'?", a: "homer" }
        ],
        general: [
            { q: "What is the largest organ in the human body?", a: "skin" },
            { q: "How many time zones does Russia have?", a: "11" },
            { q: "What is the currency of Switzerland?", a: "franc" },
            { q: "How many permanent members are in the UN Security Council?", a: "5" },
            { q: "What is the rarest blood type?", a: "ab" },
            { q: "What is the only mammal capable of true flight?", a: "bat" },
            { q: "How many teeth does an adult human typically have?", a: "32" },
            { q: "What is the largest species of shark?", a: "whale" },
            { q: "What language has the most native speakers?", a: "mandarin" },
            { q: "How many bones are in the adult human body?", a: "206" },
            { q: "What is the fastest land animal?", a: "cheetah" },
            { q: "What precious stone is red in color?", a: "ruby" },
            { q: "How many hearts does an octopus have?", a: "3" },
            { q: "What is the largest bird in the world?", a: "ostrich" },
            { q: "What is the smallest country in the world by area?", a: "vatican" },
            { q: "What is the main ingredient in guacamole?", a: "avocado" },
            { q: "How many strings does a standard guitar have?", a: "6" },
            { q: "What is the largest mammal in the world?", a: "whale" },
            { q: "What is the currency of South Africa?", a: "rand" },
            { q: "How many chromosomes do humans have?", a: "46" },
            { q: "What is the tallest mammal on Earth?", a: "giraffe" },
            { q: "What is the most spoken language in South America?", a: "spanish" },
            { q: "How many players are in a standard chess set per side?", a: "16" },
            { q: "What is the fear of heights called?", a: "acrophobia" },
            { q: "What is the largest desert in Asia?", a: "gobi" }
        ],
        technology: [
            { q: "What year was the first iPhone released?", a: "2007" },
            { q: "What does HTTP stand for (first word)?", a: "hypertext" },
            { q: "Who is considered the father of computer science?", a: "turing" },
            { q: "What company created the Android operating system?", a: "google" },
            { q: "What year was Facebook founded?", a: "2004" },
            { q: "What does SSD stand for (first word)?", a: "solid" },
            { q: "Who invented the World Wide Web?", a: "berners" },
            { q: "What programming language was created by James Gosling?", a: "java" },
            { q: "What year was Wikipedia launched?", a: "2001" },
            { q: "What does IoT stand for (first word)?", a: "internet" },
            { q: "What company makes the PlayStation gaming console?", a: "sony" },
            { q: "What is the most used programming language for web development?", a: "javascript" },
            { q: "What year was the first text message sent?", a: "1992" },
            { q: "Who founded SpaceX?", a: "musk" },
            { q: "What does VPN stand for (first word)?", a: "virtual" },
            { q: "What company developed the Kindle e-reader?", a: "amazon" },
            { q: "What year did Bitcoin launch?", a: "2009" },
            { q: "What does SQL stand for (first word)?", a: "structured" },
            { q: "Who co-founded Apple with Steve Jobs?", a: "wozniak" },
            { q: "What operating system is used by most web servers?", a: "linux" },
            { q: "What year was Twitter founded?", a: "2006" },
            { q: "What does API stand for (first word)?", a: "application" },
            { q: "What company created the Xbox?", a: "microsoft" },
            { q: "What is the name of Google's AI assistant?", a: "gemini" },
            { q: "What year was Netflix founded?", a: "1997" }
        ],
        india: [
            { q: "What is the longest river in India?", a: "ganga" },
            { q: "Which Indian state has the longest coastline?", a: "gujarat" },
            { q: "What is the highest civilian award in India?", a: "bharat" },
            { q: "Who wrote the Indian national anthem?", a: "tagore" },
            { q: "What is the largest state of India by area?", a: "rajasthan" },
            { q: "In what year was the Indian Constitution adopted?", a: "1950" },
            { q: "What is India's largest public sector bank?", a: "sbi" },
            { q: "Which city is known as the Silicon Valley of India?", a: "bangalore" },
            { q: "What is the national aquatic animal of India?", a: "dolphin" },
            { q: "Who designed the Indian Parliament building?", a: "lutyens" },
            { q: "What is the oldest mountain range in India?", a: "aravalli" },
            { q: "Which Indian city is called the City of Joy?", a: "kolkata" },
            { q: "What is the national tree of India?", a: "banyan" },
            { q: "Who was the first Indian to win an Olympic individual gold?", a: "bindra" },
            { q: "What is the largest desert in India?", a: "thar" },
            { q: "Which Indian state is known as God's Own Country?", a: "kerala" },
            { q: "What is the national game of India?", a: "hockey" },
            { q: "Who was the first woman President of India?", a: "patil" },
            { q: "What is the highest peak in India?", a: "kangchenjunga" },
            { q: "Which Indian city hosts the Pushkar Camel Fair?", a: "pushkar" },
            { q: "What river is the Statue of Unity located near?", a: "narmada" },
            { q: "Who is known as the Missile Man of India?", a: "kalam" },
            { q: "What is India's largest union territory by area?", a: "ladakh" },
            { q: "Which dance form originated in Tamil Nadu?", a: "bharatanatyam" },
            { q: "What is the currency symbol for Indian Rupee?", a: "₹" }
        ]
    },
};

// Export for use in game.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = VaultQuestions;
}
